# Generated by Django 6.0 on 2025-12-11 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_list',
            new_name='Todo',
        ),
    ]
