# Generated by Django 6.0 on 2025-12-11 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_todo_list_todo_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Todo',
            new_name='Todo_list',
        ),
    ]
