# Generated by Django 6.0 on 2025-12-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_todo_todo_todo_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_detail',
            field=models.CharField(default='TODO OBJECT BLANK', max_length=125),
        ),
    ]
