# Generated by Django 6.0 on 2025-12-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_todo_todo_detail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(default="BLANK CLASS", max_length=45)),
                (
                    "assignment_title",
                    models.CharField(default="BLANK ASSIGNMENT TITLE", max_length=125),
                ),
                (
                    "assignment_detail",
                    models.TextField(default="BLANK ASSIGNMENT DETAILS"),
                ),
            ],
        ),
    ]
