# Generated by Django 6.0 on 2025-12-12 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_homework"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homework",
            old_name="assignment_detail",
            new_name="detail",
        ),
        migrations.RenameField(
            model_name="homework",
            old_name="assignment_title",
            new_name="title",
        ),
        migrations.AddField(
            model_name="homework",
            name="due_date",
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
