# Generated by Django 6.0 on 2025-12-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_assignment_detail_homework_detail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="class_name",
            field=models.CharField(max_length=45),
        ),
    ]
