# Generated by Django 6.0 on 2025-12-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_homework_class_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="class_name",
            field=models.CharField(default="BLANK CLASS", max_length=45),
        ),
    ]
